#!/bin/env bash

: ${prefix:="."}
: ${delete:=0}

while getopts ":dp:*" option
do
 case "${option}"
 in
 p) prefix=${OPTARG};;
 d) delete=1;;
 *) echo "Invalid option!"
 esac
done
shift $((OPTIND-1))

prefix="$(sed 's/\/$//' <<< $prefix)"

echo "Checking for Anaconda3 and Snakemake"

conda -V &> /dev/null
if [ $? -ne 0 ]; then
  echo "Please install Anaconda or Miniconda"
  exit 1
fi

python -c "import sys; sys.exit(0) if sys.version_info >= (3, 0) else sys.exit(1)"

if [ $? -ne 0 ]; then
  echo "Please install or activate a python3 environment"
  exit 2
fi

if [ "$(conda list snakemake | grep snakemake | wc -l)" -eq 0 ]; then
  echo "Installing Snakemake"
  conda install snakemake
fi

echo Making directory
mkdir -p ${prefix}/scripts

echo Loading R:
module load R
echo Installing R packages:
Rscript .files/installRpackages.R --vanilla --slave

echo Copying files
for i in .files/{Snakefile,cluster.yaml,config.yaml,run}; do
  cp $i $prefix
done

for i in .files/scripts/{__init__.py,parse_config.py,Post_imputation.Rmd,fix_HRCvcf.R}; do
  cp $i ${prefix}/scripts/
done

mkdir ${prefix}/.snakejob

echo Adding Anaconda path to config file

pypath="$(dirname $(which python))"
is_conda="$(echo $pypath | grep anaconda | wc -l)"

if [ $is_conda -eq 1 ]; then
  echo "anaconda: $pypath" >> ${prefix}/config.yaml
else
  echo "Could not find anaconda path. Please enter Anaconda3 path manually."
  echo "anaconda: " >> ${prefix}/config.yaml
fi


if [ $delete -eq 1 ]; then
  echo "Deleting install files."
  rm -r .files
  rm -- "$0"
  if [ $prefix != "." ] && [ ${PWD##*/} = "imputePrep" ]; then
    cd ..
    rm -r flipPrep
  fi
fi

echo
echo "You can now run the pipeline on the cluster by navigating to the install"
echo "folder and running ./run -j [number of desired threads]"
echo
echo "Place PLINK binary filesets in the target directory, or in a folder"
echo "specified under \"directory\" in config.yaml"
echo

exit 0
