#!/usr/bin/env bash

set -e

curdir="$(pwd)"
jname="$(basename $curdir)"

bsub=("bsub -K -J $jname:{rule}:{wildcards}"
"-P {cluster.project} -q {cluster.queue} -m {cluster.partition}"
"-n {cluster.cores} -R \"span[hosts=1] select[mem>{cluster.mem}]"
"rusage[mem={cluster.mem}]\" -W {cluster.time} -L /bin/bash"
"-oo .snakejob/{rule}:{wildcards}.stdout"
"-eo .snakejob/{rule}:{wildcards}.stderr < ")

snakemake -u cluster.yaml --cluster-sync "${bsub[*]}" \
  --local-cores 4 --max-jobs-per-second 1 "$@"
